In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
df = pd.read_csv('/content/social_media_addiction_dataset (1).csv')
df.head(10)

,daily_screen_time,app_opens,sleep_hours,stress_level,study_interruptions,night_usage,addiction_level
0,5.4,67,3.8,1,2,No,Moderate
1,4.3,10,6.9,2,7,No,Low
2,7.0,48,5.4,9,3,No,Moderate
3,12.0,16,6.7,2,0,No,Low
4,8.8,25,6.0,3,15,No,Moderate
5,9.8,45,5.0,3,13,Yes,Moderate
6,10.9,53,7.5,6,8,No,Moderate
7,11.7,37,4.3,6,1,Yes,Moderate
8,7.5,51,7.4,10,9,No,High
9,3.9,76,4.5,10,14,No,High


In [4]:
print(df.columns)

Index(['daily_screen_time', 'app_opens', 'sleep_hours', 'stress_level',
       'study_interruptions', 'night_usage', 'addiction_level'],
      dtype='object')


In [6]:
X = df.drop('addiction_level', axis=1)
y = df['addiction_level']

In [7]:
le = LabelEncoder()
y = le.fit_transform(y)

In [8]:
X = pd.get_dummies(X)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
model = SVC(kernel='linear')
model.fit(X_train, y_train)

SVC(kernel='linear')

In [21]:
y_pred = model.predict(X_test)

In [22]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9


In [23]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.74      0.86      0.79        29
           1       0.83      0.86      0.84        22
           2       0.95      0.91      0.93       149

    accuracy                           0.90       200
   macro avg       0.84      0.88      0.86       200
weighted avg       0.91      0.90      0.90       200



In [24]:
print(confusion_matrix(y_test, y_pred))

[[ 25   0   4]
 [  0  19   3]
 [  9   4 136]]


In [25]:
import joblib

In [26]:
joblib.dump(model, 'svm_model.joblib')

['svm_model.joblib']

In [28]:
loaded_model = joblib.load('svm_model.joblib')
print("model loaded successfully")

model loaded successfully
